import Image from 'next/image';
import { business, whatsappUrl } from '@/config/business';
import { BookingLink, Header } from '@/components/Header';
import { SectionTitle } from '@/components/Section';

const Arrow = () => <span aria-hidden>↗</span>;
export default function Home() {
 const booking = whatsappUrl();
 const schema = { '@context': 'https://schema.org', '@type': 'HealthAndBeautyBusiness', name: business.businessName, address: { '@type': 'PostalAddress', streetAddress: business.address[0], addressLocality: business.city, addressRegion: business.region, addressCountry: 'BR' }, sameAs: [business.instagram, business.googleMaps] };
 return <><Header/><main>
  <section className="hero" id="inicio"><div className="heroCopy"><p className="kicker">Cuidado facial • Curitiba</p><h1>Uma abordagem precisa para a <em>singularidade</em> da sua pele.</h1><p className="lead">Especialista em cuidados para melasma e tratamentos faciais, com avaliação individual e atenção a cada etapa.</p><div className="actions"><BookingLink href={booking} label="Agendar minha avaliação"/><a className="textLink" href="#tratamentos">Conhecer tratamentos <Arrow/></a></div><p className="location">⌖ Atendimento no Centro de Curitiba – PR</p></div><div className="heroImage"><Image src={business.images.hero.src} alt={business.images.hero.alt} fill priority sizes="(max-width: 800px) 100vw, 50vw"/><div className="imageNote"><span>Especialidade</span><strong>Melasma &<br/>cuidados faciais</strong></div></div></section>
  <aside className="trust" aria-label="Diferenciais"><div><span className="stars">★★★★★</span><p>Perfil público no Google</p></div><div><strong>Curitiba — PR</strong><p>Atendimento no Centro</p></div><div><strong>Olhar individual</strong><p>Cuidado pensado para cada pele</p></div></aside>
  <section className="editorial" id="especialidade"><div className="portrait"><Image src={business.images.specialty.src} alt={business.images.specialty.alt} fill sizes="(max-width:800px) 100vw, 45vw"/><span className="vertical">PELE • CIÊNCIA • CUIDADO</span></div><div className="editorialCopy"><SectionTitle eyebrow="Especialidade">Um cuidado individualizado para o <em>melasma.</em></SectionTitle><p>Cada pele tem características, sensibilidades e necessidades próprias. Por isso, a avaliação é o ponto de partida para compreender o seu momento e definir uma estratégia de cuidados personalizada.</p><p>Sem fórmulas prontas: uma abordagem responsável, construída com atenção e acompanhamento.</p><BookingLink href={booking} label="Agendar avaliação" className="underLink"/></div></section>
  <section className="protocol"><p className="script">Meu</p><SectionTitle eyebrow="Abordagem exclusiva" light>Protocolo<br/>Brenda Emanuelly</SectionTitle><div className="protocolText"><p>Uma abordagem personalizada divulgada pela profissional, pensada a partir da leitura individual de cada pele.</p><p>Os detalhes e a indicação são definidos durante a avaliação, respeitando as particularidades de cada paciente.</p></div></section>
  <section className="services" id="tratamentos"><div className="servicesHead"><SectionTitle eyebrow="Cuidados faciais">Tratamentos com propósito,<br/><em>atenção em cada detalhe.</em></SectionTitle><p>Uma seleção essencial de cuidados para acompanhar diferentes necessidades da pele.</p></div><div className="serviceGrid">{business.services.map(s => <article key={s.title}><span>{s.eyebrow}</span><h3>{s.title}</h3><p>{s.description}</p><a href="#localizacao" aria-label={`Saiba mais sobre ${s.title}`}>Saber mais <Arrow/></a></article>)}</div><div className="center"><BookingLink href={booking} label="Quero cuidar da minha pele"/></div></section>
  <section className="experience"><div><SectionTitle eyebrow="A experiência">Presença, escuta e cuidado em <em>cada etapa.</em></SectionTitle><div className="steps">{['Avaliação individual','Atendimento personalizado','Acompanhamento','Cuidado em cada etapa'].map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></div><div className="experienceImage"><Image src={business.images.experience.src} alt={business.images.experience.alt} fill sizes="(max-width:800px) 100vw, 42vw"/></div></section>
  <section className="about" id="sobre"><div className="aboutImage"><Image src={business.images.professional.src} alt={business.images.professional.alt} fill sizes="(max-width:800px) 100vw, 40vw"/><small>Imagem editorial provisória</small></div><div><SectionTitle eyebrow="Sobre a profissional">Conheça<br/><em>{business.professionalName}</em></SectionTitle><p>{business.bio}</p><ul><li>{business.credential}</li><li>Especialista em melasma</li><li>Atuação com tratamentos faciais</li></ul><a className="underLink" href={business.instagram} target="_blank" rel="noreferrer">Conhecer no Instagram <Arrow/></a></div></section>
  {business.testimonials.length === 0 && <section className="google"><span className="quote">“</span><div><p className="kicker">Presença no Google</p><h2>Conheça o perfil público da clínica.</h2><p>Consulte informações e avaliações diretamente na fonte, sem depoimentos reproduzidos nesta demonstração.</p></div><a className="button outline" href={business.googleMaps} target="_blank" rel="noreferrer">Ver perfil no Google <Arrow/></a></section>}
  <section className="locationSection" id="localizacao"><div><SectionTitle eyebrow="Localização">Seu cuidado no<br/><em>coração de Curitiba.</em></SectionTitle><h3>{business.businessName}</h3><address>{business.address.map(x=><span key={x}>{x}</span>)}</address><a className="button" href={business.googleMaps} target="_blank" rel="noreferrer">Ver no Google Maps <Arrow/></a></div><iframe title={`Mapa de ${business.businessName}`} src={business.mapEmbed} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></section>
  <section className="finalCta"><span className="kicker">Comece pela avaliação</span><h2>Sua pele merece um cuidado<br/><em>pensado para ela.</em></h2><p>Agende uma conversa para compreender as necessidades da sua pele e conhecer as possibilidades de cuidado.</p><BookingLink href={booking} label="Agendar minha avaliação" className="button lightButton"/></section>
 </main><footer><div className="brand footerBrand"><b>BRE</b><span>{business.businessName}<small>ESTÉTICA AVANÇADA</small></span></div><p>{business.city} — {business.region}</p><nav><a href={business.instagram}>Instagram</a><a href={business.googleMaps}>Google Maps</a></nav><small>Demonstração de website — conteúdo sujeito à aprovação da profissional.</small></footer>
 {booking && <a className="floating" href={booking} target="_blank" rel="noreferrer" aria-label="Agendar pelo WhatsApp">WA</a>}
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify(schema)}}/></>;
}
